FROM docker.io/moby/buildkit:v1.2.0 as buildkit

# Skonfiguruj zmienne środowiskowe
ENV DOCKER_BUILDKIT=1 \
    DOCKER_CLI_EXPERIMENTAL=enabled

# Skopiuj klucz prywatny SSH do kontenera
RUN mkdir /root/.ssh
COPY id_rsa /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa

# Dodaj klucz do znanych hostów SSH
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

# Sklonuj repozytorium
FROM alpine/git as clone
WORKDIR /app
RUN --mount=type=ssh git clone git@github.com:MarcineQu/lab6_spraw.git .

# Zbuduj obraz za pomocą silnika Buildkit
FROM buildkit as builder
WORKDIR /app
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=bind,source="$(pwd)",target=/app \
    /usr/bin/buildctl build \
        --frontend=dockerfile.v0 \
        --local context=/app \
        --local dockerfile=/app/Dockerfile \
        --output type=image,name=marcinequ/lab6:latest

# Uruchom obraz
FROM alpine
CMD ["/bin/sh"]